
package GUI;

import autoposto.Combustivel;
import autoposto.CombustivelDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CombustivelPanel extends javax.swing.JPanel {

    private final FramePrincipal frame;
    private final ArrayList<Combustivel> listaCombustivel;
    
    /**
     * Metódo construtor classe CombustivelPanel.
     * @param frame 
     */
    public CombustivelPanel(FramePrincipal frame){
        initComponents();
        this.frame = frame;
        
        CombustivelDAO comb = new CombustivelDAO();
        listaCombustivel = comb.obterLista();
    }
    
    public void carregarValores(){
        tValorEtanol.setText(listaCombustivel.get(1).getDescricao());
    }

    /**
     * Recebe um objeto Combustivel e realiza a chamada de um JOptionPane para definir o valor do combustível.
     * @param Object Combustivel
     */
    private float alterarValor(Combustivel comb) {
        float valor = 0;
        while ( valor == 0) {
            valor = Float.parseFloat(JOptionPane.showInputDialog("Alterar o valor "+comb.getDescricao()+":"));
            if (valor == 0) {
                JOptionPane.showMessageDialog(null, "Valor não preenchido.");
            }
        }
        JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
        return valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDiesel = new javax.swing.JToggleButton();
        tValorDiesel = new javax.swing.JLabel();
        lCifrao1 = new javax.swing.JLabel();
        bEtanol = new javax.swing.JToggleButton();
        lCifrao2 = new javax.swing.JLabel();
        tValorEtanol = new javax.swing.JLabel();
        tValorGasolina = new javax.swing.JLabel();
        bGasolina = new javax.swing.JToggleButton();
        lCifrao3 = new javax.swing.JLabel();
        bVoltar = new javax.swing.JToggleButton();

        bDiesel.setText("DIESEL");
        bDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDieselActionPerformed(evt);
            }
        });

        tValorDiesel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tValorDiesel.setText("0,00");

        lCifrao1.setText("R$");

        bEtanol.setText("ETANOL");
        bEtanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEtanolActionPerformed(evt);
            }
        });

        lCifrao2.setText("R$");

        tValorEtanol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tValorEtanol.setText("0,00");

        tValorGasolina.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tValorGasolina.setText("0,00");

        bGasolina.setText("GASOLINA");
        bGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGasolinaActionPerformed(evt);
            }
        });

        lCifrao3.setText("R$");

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCifrao1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tValorDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCifrao2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tValorEtanol, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bEtanol, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCifrao3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tValorGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bVoltar)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDiesel)
                    .addComponent(tValorDiesel)
                    .addComponent(lCifrao1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEtanol)
                    .addComponent(tValorEtanol)
                    .addComponent(lCifrao2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGasolina)
                    .addComponent(tValorGasolina)
                    .addComponent(lCifrao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(bVoltar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        // Voltar tela de opções
        frame.setPanel(new OptionsPanel(frame));
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDieselActionPerformed
        // Abre o JOption para alterar o valor do Diesel (index = 1)
        listaCombustivel.get(1).setValor(this.alterarValor(listaCombustivel.get(1)));
    }//GEN-LAST:event_bDieselActionPerformed

    private void bEtanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEtanolActionPerformed
        // Abre o JOption para alterar o valor do Etanol (index = 2)
        listaCombustivel.get(2).setValor(this.alterarValor(listaCombustivel.get(2)));
    }//GEN-LAST:event_bEtanolActionPerformed

    private void bGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGasolinaActionPerformed
        // Abre o JOption para alterar o valor da Gasolina (index = 3)
        listaCombustivel.get(3).setValor(this.alterarValor(listaCombustivel.get(3)));
    }//GEN-LAST:event_bGasolinaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bDiesel;
    private javax.swing.JToggleButton bEtanol;
    private javax.swing.JToggleButton bGasolina;
    private javax.swing.JToggleButton bVoltar;
    private javax.swing.JLabel lCifrao1;
    private javax.swing.JLabel lCifrao2;
    private javax.swing.JLabel lCifrao3;
    private javax.swing.JLabel tValorDiesel;
    private javax.swing.JLabel tValorEtanol;
    private javax.swing.JLabel tValorGasolina;
    // End of variables declaration//GEN-END:variables
}
