/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author danil
 */
public class CombustivelPanel extends javax.swing.JPanel {

    FramePrincipal frame;
    public CombustivelPanel() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDiesel = new javax.swing.JToggleButton();
        tValorDiesel = new javax.swing.JLabel();
        lCifrao1 = new javax.swing.JLabel();
        bEtanol = new javax.swing.JToggleButton();
        lCifrao2 = new javax.swing.JLabel();
        tValorEtanol = new javax.swing.JLabel();
        tValorGasolina = new javax.swing.JLabel();
        bGasolina = new javax.swing.JToggleButton();
        lCifrao3 = new javax.swing.JLabel();
        bVoltar = new javax.swing.JToggleButton();

        bDiesel.setText("DIESEL");
        bDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDieselActionPerformed(evt);
            }
        });

        tValorDiesel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tValorDiesel.setText("0,00");

        lCifrao1.setText("R$");

        bEtanol.setText("ETANOL");
        bEtanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEtanolActionPerformed(evt);
            }
        });

        lCifrao2.setText("R$");

        tValorEtanol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tValorEtanol.setText("0,00");

        tValorGasolina.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tValorGasolina.setText("0,00");

        bGasolina.setText("GASOLINA");
        bGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGasolinaActionPerformed(evt);
            }
        });

        lCifrao3.setText("R$");

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCifrao1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tValorDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCifrao2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tValorEtanol, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bEtanol, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCifrao3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tValorGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bVoltar)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDiesel)
                    .addComponent(tValorDiesel)
                    .addComponent(lCifrao1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEtanol)
                    .addComponent(tValorEtanol)
                    .addComponent(lCifrao2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGasolina)
                    .addComponent(tValorGasolina)
                    .addComponent(lCifrao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(bVoltar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        // Volta na tela de opções
        OptionsPanel op = new OptionsPanel();
        frame.setPanel(op);
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDieselActionPerformed
        // Abre o JOption para alterar o valor do Diesel
    }//GEN-LAST:event_bDieselActionPerformed

    private void bEtanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEtanolActionPerformed
        // Abre o JOption para alterar o valor do Etanol
    }//GEN-LAST:event_bEtanolActionPerformed

    private void bGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGasolinaActionPerformed
        // Abre o JOption para alterar o valor da Gasolina
    }//GEN-LAST:event_bGasolinaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bDiesel;
    private javax.swing.JToggleButton bEtanol;
    private javax.swing.JToggleButton bGasolina;
    private javax.swing.JToggleButton bVoltar;
    private javax.swing.JLabel lCifrao1;
    private javax.swing.JLabel lCifrao2;
    private javax.swing.JLabel lCifrao3;
    private javax.swing.JLabel tValorDiesel;
    private javax.swing.JLabel tValorEtanol;
    private javax.swing.JLabel tValorGasolina;
    // End of variables declaration//GEN-END:variables
}
