/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 * 
 * @author danil
 */
public class OptionsPanel extends javax.swing.JPanel {

    private FramePrincipal frame;
    
    public OptionsPanel() {
        initComponents();
    }
    
    public OptionsPanel(FramePrincipal frame){
        initComponents();
        this.frame =  frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAtualizar = new javax.swing.JButton();
        bCombustivel = new javax.swing.JToggleButton();
        bRelatorio = new javax.swing.JToggleButton();
        bTeste = new javax.swing.JToggleButton();
        bControle = new javax.swing.JToggleButton();

        bAtualizar.setText("Atualizar Valores");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        bCombustivel.setText("Combustível");
        bCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCombustivelActionPerformed(evt);
            }
        });

        bRelatorio.setText("Relatório");
        bRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRelatorioActionPerformed(evt);
            }
        });

        bTeste.setText("Teste (GAS/ALC)");
        bTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTesteActionPerformed(evt);
            }
        });

        bControle.setText("Controle Bomba");
        bControle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bControleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(bCombustivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bControle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTeste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRelatorio)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bControleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bControleActionPerformed
        // chamar tela de controle
        ControlePanel co = new ControlePanel();
        frame.setPanel(co);
    }//GEN-LAST:event_bControleActionPerformed

    private void bCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCombustivelActionPerformed
        // chama tela de Combustivel
        CombustivelPanel cb = new CombustivelPanel();
        frame.setPanel(cb);
    }//GEN-LAST:event_bCombustivelActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
        // chama tela de atualizar valores dos combustíveis
        ValorCombustivelPanel va = new ValorCombustivelPanel();
        frame.setPanel(va);
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void bTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTesteActionPerformed
        // chama tela de teste
        TestePanel te = new TestePanel();
        frame.setPanel(te);
    }//GEN-LAST:event_bTesteActionPerformed

    private void bRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRelatorioActionPerformed
        // Chama a tela de Relatório
        RelatorioPanel rp = new RelatorioPanel();
        frame.setPanel(rp);
    }//GEN-LAST:event_bRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizar;
    private javax.swing.JToggleButton bCombustivel;
    private javax.swing.JToggleButton bControle;
    private javax.swing.JToggleButton bRelatorio;
    private javax.swing.JToggleButton bTeste;
    // End of variables declaration//GEN-END:variables
}
